name = "dfmailbox"
version = "0.0.1"

description = "A decentralized way to pass messages to other DiamondFire plots"
licences = ["GPL-3.0-or-later"]
repository = { type = "github", user = "DynamicCake", repo = "dfmailbox" }
links = [{ title = "Website", href = "https://dftools.dev/" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
cors_builder = ">= 2.0.4 and < 3.0.0"
pog = ">= 4.0.0 and < 5.0.0"
youid = ">= 1.5.0 and < 2.0.0"
ed25519 = ">= 1.4.3 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_time = ">= 1.5.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
ewe = ">= 2.1.1 and < 3.0.0"
json_value = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 4.0.0 and < 5.0.0"
